### ISSUE TITLE
Is this benchmark support to test TDengine?

### ISSUE THREAD

**Issue by tomcraz** [thulab/iotdb-benchmark#108]
我们正在调研和TDengine的性能对比，看论坛上说这个项目能开展IoTDB和TDengine的对比测试，可看了下源码好像没有TDengine的测试功能，不知道是否能够开发TDengine的测试功能？

**Comment by dullduck** [comment]
我看最新的config.properties 有taosdb，不知道真的支持没有

**Comment by dullduck** [comment]
刚刚试了一下：插入可以测试
![image](https://user-images.githubusercontent.com/6882249/112115183-ddd57600-8bf3-11eb-8ad8-42322a1f84a4.png)

**Comment by stormbroken** [comment]
We support TDengine now.
Related PRs are PR #192 and PR #197 
Thanks!
