### ISSUE TITLE
Bug in class SingletonWorkload

### ISSUE THREAD

**Issue by nlosilva1** [thulab/iotdb-benchmark#110]
There is a logical bug in class `SingletonWorkload`. In its `getOneBatch()` function, the `case of` statement can't fit to the right meaning of `config.OVERFLOW_MODE`. In fact, `case 0` should be  `getDistOutOfOrderBatch()`, and `case 1` should be `getLocalOutOfOrderBatch()`.

**Comment by liuruiyiyang** [comment]
Fixed in PR#111
