### ISSUE TITLE
编译的时候出错

### ISSUE THREAD

**Issue by Frank-KunLi** [thulab/iotdb-benchmark#131]
mvn clean package -Dmaven.test.skip=true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< cn.edu.tsinghua:iotdb-benchmark >-------------------
[INFO] Building iotdb-benchmark 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.apache.iotdb:iotdb-jdbc:jar:0.11.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.iotdb:iotdb-session:jar:0.11.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.514 s
[INFO] Finished at: 2020-08-13T15:31:32+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project iotdb-benchmark: Could not resolve dependencies for project cn.edu.tsinghua:iotdb-benchmark:jar:0.0.1: The following artifacts could not be resolved: org.apache.iotdb:iotdb-jdbc:jar:0.11.0-SNAPSHOT, org.apache.iotdb:iotdb-session:jar:0.11.0-SNAPSHOT: Could not find artifact org.apache.iotdb:iotdb-jdbc:jar:0.11.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jixuan1989** [comment]
这个错误是因为IoTDB的0.11版本尚未发布。

简单的话，可以下载apache iotdb的源码 并 mvn install -DskipTests
让本地拥有相关jar包。 https://github.com/apache/incubator-iotdb

麻烦点的话，需要修改pom文件，将版本降低到0.10.0。再修复下tsdb/IoTDBSession  中的报错信息
