### ISSUE TITLE
在初始化项目使用mvn clean package -Dmaven.test.skip=true命令出现错误

### ISSUE THREAD

**Issue by linxinxin778** [thulab/iotdb-benchmark#182]
使用mvn clean package -Dmaven.test.skip=true 后显示 Benchmark Core FAILURE,然后就BUILD FAILURE 错误原因如下：
Failed to execute goal on project core: Could not resolve dependencies for project cn.edu.tsinghua:core:jar:0.0.1: Failed to collect dependencies at org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)] -> [Help 1]

该怎么解决，没法使用，谢谢，急求

**Comment by stormbroken** [comment]
看起来应该是你的maven包解决的过程中出现了问题。
也许你可以查一下这一句话相关的解决方案，Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net

**Comment by stormbroken** [comment]
或者也许你可以考虑替换一下你的maven的镜像源

**Comment by linxinxin778** [comment]
> 或者也许你可以考虑替换一下你的maven的镜像源

我试过了换镜像源，还是会出现这个问题，我找了一下出问题的镜像网站上cn.edu.tsinghua中没有IoTDB-benchmark，是什么原因，是我maven的镜像源 有问题，找的地方不对吗

**Comment by stormbroken** [comment]
哦哦，是因为IoTDB-Benchmark的包没有被自动收集上去，所以你需要在这个项目的根目录执行mvn clean package -Dmaven.test.skip=true命令来完成所有的打包操作，不知道执行这个命令的路径是？

**Comment by linxinxin778** [comment]
> 哦哦，是因为IoTDB-Benchmark的包没有被自动收集上去，所以你需要在这个项目的根目录执行mvn clean package -Dmaven.test.skip=true命令来完成所有的打包操作，不知道执行这个命令的路径是？

**Comment by linxinxin778** [comment]
> 此外，也许你可以尝试将本地的maven镜像替换成阿里云的镜像，或者不设置镜像来解决这个依赖的问题

执行的路径是项目的根目录，我更改一下源，不设置镜像试试

**Comment by linxinxin778** [comment]
> 另外，也许你可以尝试将本地的假象变成阿里云的镜像，或者设置不清晰来解决这个依赖的问题

我换了阿里的镜像源显示BUILD SUCCESS了，但是使用./benchmark.sh命令显示错误: 找不到或无法加载主类 cn.edu.tsinghua.iotdb.benchmark.App  是什么原因

**Comment by stormbroken** [comment]
嗯嗯，不是在项目的根目录执行benchmark.sh，而是进入到你想要测试的对应的数据库的文件夹中进行执行，以IoTDB-0.12为例，你可以进入到/iotdb-0.12/target/iotdb-0.12-0.0.1这个文件夹，执行这个文件夹中的benchmark.sh来启动benchmark，此时你的benchmark的运行的conf文件在/iotdb-0.12/target/iotdb-0.12-0.0.1/conf文件夹中，你可以修改对应的配置文件。其他的数据库也是相似的。

**Comment by linxinxin778** [comment]
> 嗯嗯，不是在项目的根目录执行benchmark.sh，而是进入到你想要测试的对应的数据库的文件夹中进行执行，以IoTDB-0.12为例，你可以进入到/iotdb-0.12/target/iotdb-0.12-0.0.1这个文件夹，执行这个文件夹中的benchmark.sh来启动benchmark，此时你的benchmark的运行的conf文件在/iotdb-0.12/target/iotdb-0.12-0.0.1/conf文件夹中，你可以修改对应的配置文件。其他的数据库也是相似的。

可以了可以了，终于完美解决了，万分感谢

**Comment by stormbroken** [comment]
好的，没问题的话，就可以close了，欢迎使用！
