### ISSUE TITLE
influxdb2 写入数据为何用HTTP 不用JAVA客户端？

### ISSUE THREAD

**Issue by xinzhongtianxia** [thulab/iotdb-benchmark#187]
我用influx最新的的java client测了几天，暂时没发现问题
https://github.com/influxdata/influxdb-client-java
<dependency>
    <groupId>com.influxdb</groupId>
    <artifactId>influxdb-client-java</artifactId>
    <version>3.2.0</version>
</dependency>

还有似乎每次POST时，都重新开了连接？
![image](https://user-images.githubusercontent.com/16996964/131099962-9997cc91-67b6-47fb-9714-2c2416495e21.png)

**Comment by stormbroken** [comment]
因为如果使用最新的influxdb的java client在长时间压测的过程中有极大概率出现OOM的问题，所以我切换成了HTTP的方式。

**Comment by stormbroken** [comment]
至于每次开启新的连接，是每个batch的写入开启一次连接，请问您有什么更好的建议嘛？

**Comment by xinzhongtianxia** [comment]
> 因为如果使用最新的influxdb的java client在长时间压测的过程中有极大概率出现OOM的问题，所以我切换成了HTTP的方式。

可以试试最新版的java客户端，我持续压测了十几个小时，客户端倒是没啥问题
influxdb本身倒是会oom，不过应该这和客户端没关系

**Comment by stormbroken** [comment]
好的，我来确认一下

**Comment by ytyou** [comment]
如果influxdb的客户端不能用，不知可否用HTTP的连接池，如Apache的PoolingHttpClientConnectionManager？

**Comment by stormbroken** [comment]
influxdb的客户端是可用的，并且在稍早版本中使用的是influxdb的客户端，但是会存在客户端OOM的问题，因此切换成了HTTP请求方式，后续我们来确定一下更佳的实现方式。

**Comment by SpriCoder** [comment]
我们在这个 PR#265 中修复了这个问题
