### ISSUE TITLE
OpenTSDB中实现“带时间过滤的聚合查询”（Q4）有误

### ISSUE THREAD

**Issue by ytyou** [thulab/iotdb-benchmark#201]
Q4 （带时间过滤的聚合查询）要实现的是：select func(v1) ... from data where ...；这种查询应该只返回一个数值。比如：select count(v1) ... from data where ...; 返回的是这个时间区域里一共有多少个数据点。翻译成OpenTSDB应该是 downsample=0all-count。而现在的aggRangeQuery用的是aggregator=count。这是完全不同的意思。会返回时间区域里所有点。因而导致OpenTSDB的这种查询比其他数据库慢很多。

**Comment by stormbroken** [comment]
Ok, we will check this problem
