### ISSUE TITLE
请问为何无法编译成功？

### ISSUE THREAD

**Issue by emoRHer** [thulab/iotdb-benchmark#232]
我按照文档中的编译步骤，无法编译，更换镜像也没有成功，请问如何解决？
![image](https://user-images.githubusercontent.com/96610801/147325997-9c1c6557-0da0-42b0-9789-93da7a816fe7.png)

**Comment by ZhanGHanG9991** [comment]
我也遇到了这个问题，请问是怎么解决的？

**Comment by emoRHer** [comment]
检查2点：
1、是否是在根目录下执行的
2、不用任何镜像

**Comment by ZhanGHanG9991** [comment]
好的 我来试一下 谢谢！

**Comment by emoRHer** [comment]
么事

**Comment by ZhanGHanG9991** [comment]
确实好了 但是在iotdb-0.13编译错误，是因为0.13版本没发吗
![image](https://user-images.githubusercontent.com/34939716/149763276-e346cca1-6d53-405d-ac2b-90284a8b9c9d.png)

**Comment by emoRHer** [comment]
可能是，现在好像只有0.12版本吧，我也不清楚了

**Comment by ZhanGHanG9991** [comment]
好的 非常感谢！！

**Comment by emoRHer** [comment]
么事，我当时也安装了好几个小时👋
