### ISSUE TITLE
More query workload implementation

### ISSUE THREAD

**Issue by liukun4515** [thulab/iotdb-benchmark#44]
There are some query workloads that are not implemented.

- [x] valueRangeQuery

- [x] aggRangeQuery

- [x] aggValueQuery

- [x] aggRangeValueQuery

- [x] groupByQuery

- [x] latestPointQuery

**Comment by liukun4515** [comment]
Please this a plan to implement the remaining query workload.
@liuruiyiyang

**Comment by liuruiyiyang** [comment]
See PR #49

**Comment by liukun4515** [comment]
good job
