### ISSUE TITLE
Other DB implementation for new benchmark workload

### ISSUE THREAD

**Issue by liukun4515** [thulab/iotdb-benchmark#45]
- [x] TimeScaleDB @little-emotion 

- [x] Kariosdb

- [x] OpenTSDB

- [x] Influxdb: remaining query workload @little-emotion

**Comment by little-emotion** [comment]
timescaleDB:    https://github.com/thulab/iotdb-benchmark/pull/56
influxDB:           https://github.com/thulab/iotdb-benchmark/pull/55

**Comment by liuruiyiyang** [comment]
@nlosilva1 Could you please add the implementation of OpenTSDB in the new benchmark framework. You can refer to old code in the ```refactor_backup``` branch. Thanks :)

**Comment by liuruiyiyang** [comment]
OpenTSDB: #98
