### ISSUE TITLE
multiple slf4j binding and output issue

### ISSUE THREAD

**Issue by liuruiyiyang** [thulab/iotdb-benchmark#51]
![image](https://user-images.githubusercontent.com/20263106/55887854-e1c38580-5be0-11e9-8990-b485f52c95f1.png)
slf4j冲突的问题，还有dataset仅在read file的模式下才输出

**Comment by liukun4515** [comment]
@qiaojialin 解决下

**Comment by liukun4515** [comment]
related pr [#47](https://github.com/thulab/iotdb-benchmark/pull/47)
![image](https://user-images.githubusercontent.com/7450163/55923884-31826b00-5c3a-11e9-85e0-c17f0cf1af2c.png)
@qiaojialin

**Comment by liuruiyiyang** [comment]
fixed in PR #49
