### ISSUE TITLE
 benchmark needs to provide a secondary connection mechanism with mysql.

### ISSUE THREAD

**Issue by ZhaoXiuting** [thulab/iotdb-benchmark#72]
Step1：when benchmark is disconnected from MySQL in the test task，an exception is thrown.
![image](https://user-images.githubusercontent.com/43334810/59318492-d5030100-8cf9-11e9-909a-de1265f137cf.png)
Exception:
benchmark needs to provide a secondary connection mechanism

**Comment by liuruiyiyang** [comment]
In PR #73  the MySQL reconnection mechanism is added. You may refer to that and change the code of the branch you are using.

**Comment by ZhaoXiuting** [comment]
ok
