### ISSUE TITLE
Query results are all zeroes

### ISSUE THREAD

**Issue by PrathikShirolkar** [thulab/iotdb-benchmark#86]
I set the following parameter in the config file
OPERATION_PROPORTION=0:0:0:0:0:0:0:1:0
and all the results are zero
--------------------------------------------------Result Matrix--------------------------------------------------
Operation		okOperation	okPoint		failOperation	failPoint	elapseRate	accRate
INGESTION		0		0		0		0		0.00		0.00		
PRECISE_POINT		0		0		0		0		0.00		0.00		
TIME_RANGE		0		0		0		0		0.00		0.00		
VALUE_RANGE		0		0		0		0		0.00		0.00		
AGG_RANGE		0		0		0		0		0.00		0.00		
AGG_VALUE		0		0		0		0		0.00		0.00		
AGG_RANGE_VALUE		0		0		0		0		0.00		0.00		
GROUP_BY		0		0		0		0		0.00		0.00		
LATEST_POINT		0		0		0		0		0.00		0.00		
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------Latency (ms) Matrix-----------------------------------------------
Operation	AVG	MID_AVG	MIN	P10	P25	MEDIAN	P75	P90	P95	P99	MAX	MAX_SUM	
INGESTION	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
PRECISE_POINT	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
TIME_RANGE	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
VALUE_RANGE	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
AGG_RANGE	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
AGG_VALUE	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
AGG_RANGE_VALUE	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
GROUP_BY	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
LATEST_POINT	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	
-----------------------------------------------------------------------------------------------------------------
------Client Test Complete Time------
Fri Oct 11 12:46:41 IST 2019

**Comment by liuruiyiyang** [comment]
Hi, could you show more details of your configurations? like which TSDB are you testing and have you ingested data into the TSDB using iotdb-benchmark before the query test.

**Comment by PrathikShirolkar** [comment]
HI Rui Liu,

I am using InfluxDB to conduct the test, and yes I have ingested data into
the db
I checked the influxdb and found a test database, with many groups data in
it.

I am attaching the configuration file below.

I think this could help illustrate the probem I am facing better.
When I set the variable as follows in the config file,
OPERATION_PROPORTION=1:1:1:1:1:1:1:1:1

---------------------------------------------------------------
main measurements:
Test elapse time: 6.70 second
Create schema cost 0.21 second
--------------------------------------------------Result
Matrix--------------------------------------------------
Operation okOperation okPoint failOperation failPoint elapseRate accRate
INGESTION 249 2490 0 0 371.75 1254.01
PRECISE_POINT 209 30 0 0 4.48 23.72
TIME_RANGE 223 250 0 0 37.32 179.33
VALUE_RANGE 0 0 0 0 0.00 0.00
AGG_RANGE 0 0 0 0 0.00 0.00
AGG_VALUE 0 0 0 0 0.00 0.00
AGG_RANGE_VALUE 0 0 0 0 0.00 0.00
GROUP_BY 0 0 0 0 0.00 0.00
LATEST_POINT 0 0 0 0 0.00 0.00
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------Latency (ms)
Matrix-----------------------------------------------
Operation AVG MID_AVG MIN P10 P25 MEDIAN P75 P90 P95 P99 MAX MAX_SUM
INGESTION 15.33 12.80 6.98 8.42 9.91 12.58 15.26 20.77 27.40 110.39 113.30
1985.64
PRECISE_POINT 11.53 9.85 4.02 5.16 6.21 9.36 13.22 17.70 22.25 61.17 84.17
1264.67
TIME_RANGE 12.24 10.29 3.95 5.25 6.14 9.85 14.19 20.12 31.50 56.11 64.32
1394.12
VALUE_RANGE 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
AGG_RANGE 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
AGG_VALUE 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
AGG_RANGE_VALUE 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
GROUP_BY 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
LATEST_POINT 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
-----------------------------------------------------------------------------------------------------------------
------Client Test Complete Time------
Fri Oct 11 14:17:10 IST 2019


Ie is, even when I set all operation as 1, only ingestion, precise_point
and time_range are executed

Thanks
Prathik GS

**Comment by liuruiyiyang** [comment]
Hi, I try to reproduce your issue but the result I got is normal:
My configs are:
```
DB_SWITCH: InfluxDB
OPERATION_PROPORTION: 1:1:1:1:1:1:1:1:1
IS_CLIENT_BIND: false
CLIENT_NUMBER: 20
GROUP_NUMBER: 20
DEVICE_NUMBER: 20
SENSOR_NUMBER: 30
BATCH_SIZE: 1
LOOP: 1000
```
The result is:
```
main measurements:
Test elapse time: 3.44 second
Create schema cost 0.06 second
--------------------------------------------------Result Matrix--------------------------------------------------
Operation		okOperation	okPoint		failOperation	failPoint	elapseRate	accRate
INGESTION		2237		67110		0		0		19513.13		33691.67		
PRECISE_POINT		2197		2197		0		0		638.81		17635.21		
TIME_RANGE		2255		115005		0		0		33439.24		683300.99		
VALUE_RANGE		2138		109038		0		0		31704.25		612903.79		
AGG_RANGE		2184		2184		0		0		635.03		10991.84		
AGG_VALUE		2173		2173		0		0		631.83		7595.20		
AGG_RANGE_VALUE		2327		2327		0		0		676.61		13719.58		
GROUP_BY		2283		30833		0		0		8965.11		179474.67		
LATEST_POINT		2206		2206		0		0		641.42		10592.08		
-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------Latency (ms) Matrix-----------------------------------------------
Operation	AVG	MID_AVG	MIN	P10	P25	MEDIAN	P75	P90	P95	P99	MAX	MAX_SUM	
INGESTION	15.86	14.96	1.72	11.28	12.97	15.08	16.78	19.22	21.92	28.56	121.19	1991.89	
PRECISE_POINT	0.95	0.80	0.52	0.62	0.67	0.77	0.93	1.20	1.93	4.63	7.28	124.58	
TIME_RANGE	1.29	1.11	0.71	0.87	0.94	1.07	1.27	1.73	2.55	5.77	10.45	168.31	
VALUE_RANGE	1.40	1.20	0.76	0.94	1.02	1.15	1.37	1.96	2.88	5.71	14.48	177.90	
AGG_RANGE	1.09	0.86	0.58	0.66	0.72	0.83	1.00	1.36	2.16	5.66	97.82	198.69	
AGG_VALUE	1.67	1.43	1.01	1.14	1.20	1.34	1.66	2.21	3.27	5.98	98.18	286.10	
AGG_RANGE_VALUE	1.21	0.98	0.66	0.77	0.83	0.94	1.12	1.51	2.48	7.66	14.98	169.61	
GROUP_BY	1.24	1.02	0.70	0.80	0.86	0.97	1.16	1.69	2.68	6.21	18.35	171.80	
LATEST_POINT	0.96	0.76	0.50	0.58	0.63	0.73	0.89	1.22	2.00	4.32	97.86	208.27	
-----------------------------------------------------------------------------------------------------------------
```

My influxdb version is v1.7.7

**Comment by PrathikShirolkar** [comment]
I am using influxdb 1.7.8

**Comment by PrathikShirolkar** [comment]
I used the newer version of Apache IoTDB (v0.8.1) and now it works fine for me !
