### ISSUE TITLE
configuring time based queries

### ISSUE THREAD

**Issue by PrathikShirolkar** [thulab/iotdb-benchmark#89]
I am not able to figure out what configuration parameters to use to
(i) change the result point number for a query
(ii) set query_span
(iii) set the time interval (in percentage)
from the paper nor from the readme

**Comment by jixuan1989** [comment]
@liuruiyiyang

**Comment by liuruiyiyang** [comment]
(i) for range query, the result point number for a query is approximately equals to ```QUERY_INTERVAL / POINT_STEP``` 
(ii) query_span is the ```QUERY_INTERVAL``` parameter in the config.properties file
(iii)  the time interval of group-by query  is the ```TIME_UNIT``` parameter in the config.properties file.  The percentage is calculated by  ```TIME_UNIT / QUERY_INTERVAL * 100% ``` , where in the paper ```QUERY_INTERVAL``` is set with the length of the whole ingested time series data.

The unit of all the above parameters is millisecond.
