### ISSUE TITLE
Error in OverFlow Mode

### ISSUE THREAD

**Issue by FLOW4215** [thulab/iotdb-benchmark#92]
When I was using benchmark to test iotdb,I found an error in overflow mode.
I used almost same 'config.properties' files in two tests.
Just set 
1st : "IS_OVERFLOW=false";
2nd : "IS_OVERFLOW=true",
then I got an error when benchmark working on overflow mode:
 
![image](https://user-images.githubusercontent.com/40650975/67367181-920a4180-f5a7-11e9-9ae8-19c045d7dc5d.png)

![image](https://user-images.githubusercontent.com/40650975/67367526-3f7d5500-f5a8-11e9-8a75-ef26a4c74ee0.png)

In the same config with no overflow :
![image](https://user-images.githubusercontent.com/40650975/67367233-a9492f00-f5a7-11e9-9a4b-653e961681a2.png)

Plesae help us to check this issue.Thanks
B.R

**Comment by FLOW4215** [comment]
Update Pic2:
![image](https://user-images.githubusercontent.com/40650975/67367424-09d86c00-f5a8-11e9-8f71-7dd66f9c8b17.png)

**Comment by FLOW4215** [comment]
Update Pic2:
![image](https://user-images.githubusercontent.com/40650975/67367424-09d86c00-f5a8-11e9-8f71-7dd66f9c8b17.png)

**Comment by liuruiyiyang** [comment]
Fixed in PR #93
