### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by FLOW4215** [thulab/iotdb-benchmark#95]
When I used iotdb-benchmark[lastest] to test iotdb with below config:
![image](https://user-images.githubusercontent.com/40650975/67553946-f1e82000-f740-11e9-8e70-d3fe7648b5cc.png)
I got an error like this:
![image](https://user-images.githubusercontent.com/40650975/67554022-1643fc80-f741-11e9-8cf8-b17ebfa8960b.png)
please help us to check this.
B.R

**Comment by liuruiyiyang** [comment]
We will consider using some streaming algorithms such as T-Digest to calculate the statistics.
