### ISSUE TITLE
The allocated storage groups are uneven

### ISSUE THREAD

**Issue by FLOW4215** [thulab/iotdb-benchmark#99]
Hi：
when we used benchmark to create timeseries like this:
SG=30;Device=300;Sensor=3200
We want to manage 10 devices per storage group.But benchmark didn't create them like that.
group_0：Total timeseries number = 28800
group_1：Total timeseries number = 28800
group_2：Total timeseries number = 25600
group_3：Total timeseries number = 25600
group_4：Total timeseries number = 22400
group_5：Total timeseries number = 19200
group_6：Total timeseries number = 16000
group_7：Total timeseries number = 12800
.....

mlog.txt is bigger the 10MB.So I can not upload it in this webpage.

当设置300个设备，每个设备3200个变量的场景写入30个存储组时，设备并未平均分配到30个存储组。预期是每个存储组管理10个设备。但是现在并非如此，例如group_0内有9个设备；group_5内有6个设备。。。。

**Comment by liuruiyiyang** [comment]
Current dev branch will create  timeseries evenly among storage groups. Could you please confirm that?

**Comment by FLOW4215** [comment]
It works in dev branch.
SG=30
Device=300
Sensor=10
![image](https://user-images.githubusercontent.com/40650975/68667689-9233a680-0581-11ea-9946-060e7255526d.png)
